######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 11 17:57:38 2017
######################################################################
QT += sql

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += widget.h
FORMS += widget.ui
SOURCES += main.cpp widget.cpp
RESOURCES += xinyanqrc.qrc
